language: java
jdk:
    - oraclejdk8
services:
    - mongodb
git:
    depth: 3
branches:
    only:
        - master
before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
#node_js:
#  - "4.4.3"
#sudo: false
#before_install: npm install -g gulp
#install: npm install
#before_script: gulp build
#notifications:
#  webhooks:
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
