spring:
    application:
        name: sogo
    profiles:
        active: dev

server:
    port: 8080


logging:
    file: log.out
    level:
        ROOT: INFO                  # application log level
        com.google.maps: ERROR      # disable logging for Google Maps Services

