version: '2'
services:
    sogo-mongodb:
        container_name: sogo-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb sogo-mongodb-config
    sogo-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    sogo-mongodb-config:
        image: mongo:3.3.5
        container_name: sogo-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
